[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "scibmad"
version = "0.0.5"
authors = [
    { name = "Chanpisey Ung" }
]
description = "PyTorch–Julia binding to seamlessly optimize Julia-defined functions"
readme = "README.md"
requires-python = ">= 3.11"
license = { text = "MIT" }

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "juliacall",
    "numpy>=1.26",
    "torch>=2.0"
]

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
Homepage = "https://github.com/ChanpiseyU/scibmad"

[tool.hatch.build.targets.wheel]
packages = ["src/scibmad"]
